name: getgoods
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.5
  custom_refresh_indicator: ^2.0.1
  dio: ^5.2.0+1
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.5
  http: ^0.13.6
  http_parser: ^4.0.2
  image: ^4.0.17
  image_picker: ^0.8.9
  intl: ^0.18.1
  patterns_canvas: ^0.4.0
  path_provider: ^2.0.15
  percent_indicator: ^4.2.3
  shared_preferences: ^2.1.2
  timeago: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - config.env
  fonts:
  - family: SFTHONBURI
    fonts:
     - asset: assets/fonts/SFTHONBURI-REGULAR.TTF
     - asset: assets/fonts/SFTHONBURI-SEMIBOLD.TTF
       weight: 400
     - asset: assets/fonts/SFTHONBURI-BOLD.TTF
       weight: 700
